### ISSUE TITLE
APIからのユーザの削除ができない

### ISSUE THREAD

**Issue by pddg** [jphacks/KB_1809_2#61]
```python
Error
Traceback (most recent call last):
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/src/accounts/tests.py", line 41, in test_delete_user
    res = self.client.delete('/users/me/', data={'current_password': self.user_data['password']})
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/rest_framework/test.py", line 324, in delete
    path, data=data, format=format, content_type=content_type, **extra)
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/rest_framework/test.py", line 225, in delete
    return self.generic('DELETE', path, data, content_type, **extra)
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/rest_framework/test.py", line 238, in generic
    method, path, data, content_type, secure, **extra)
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/django/test/client.py", line 414, in generic
    return self.request(**r)
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/rest_framework/test.py", line 289, in request
    return super(APIClient, self).request(**kwargs)
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/rest_framework/test.py", line 241, in request
    request = super(APIRequestFactory, self).request(**kwargs)
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/django/test/client.py", line 495, in request
    raise exc_value
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/djoser/views.py", line 346, in me
    return self.destroy(request, *args, **kwargs)
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/djoser/views.py", line 333, in destroy
    self.perform_destroy(instance)
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/djoser/views.py", line 325, in perform_destroy
    utils.logout_user(self.request)
  File "/Users/pudding/ghq/github.com/jphacks/KB_1809_2/.venv/lib/python3.7/site-packages/djoser/utils.py", line 24, in logout_user
    settings.TOKEN_MODEL.objects.filter(user=request.user).delete()
AttributeError: type object 'Token' has no attribute 'objects'
```

issue: `https://github.com/sunscrapers/djoser/issues/257`

**Comment by pddg** [comment]
これは仕方が無いのであきらめ
